### ISSUE TITLE
Several settings not working anymore

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#10]
Folgende Settings sind broken:
- Toolgun effects:
Wenn es einmal aus ist, bleibt es für immer aus

- Toolgun sounds:
Wenn es einmal aus ist, bleibt es für immer aus

- Automatischer Cloak on Noclip
scheint bei mir garnicht zu funktionieren?

- Hide killfeed
ist reversed

- DarkRP Billboard
chat command ist immer da
billboards werden garnicht mehr gespawned egal ob an oder aus

**Comment by e8s1** [comment]
Zufällig alles Luiggi Code ..... sussy baka

**Comment by Luiggi33** [comment]
Hängt zum Großteil an der SettingChanged hook, wenn die nicht wieder geht, geht das andere auch nicht. Schau ich mir eventuell morgen an

**Comment by Luiggi33** [comment]
Toolgun effects, Killfeed und der noclip ist gefixed

**Comment by Luiggi33** [comment]
toolgun-sounds auch

**Comment by Luiggi33** [comment]
billboards auch
