### ISSUE TITLE
Double Scroll when changing multi_job_select options

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#13]
when changing settings like encrypted comms jobs, and you scroll in the popup panel, it also scrolls in the mainframe

**Comment by MenschlichTv** [comment]
update: this only happens if there is nothing more to scroll on the child, for example: if you scrolled to the bottom of the job selector, it will start scrolling on the mainframe.

Tried fixing it with :RequestFocus() but that didnt work.

**Comment by Luiggi33** [comment]
Just a idea, you could fetch the scroll bar via panel:GetVBar() and disable it while the other panel is open. I am not sure if that would work and I cant test it right now

**Comment by e8s1** [comment]
done
