### ISSUE TITLE
unstuck doesnt always work

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#15]
It doesnt work if ur stuck in the map, only if ur stuck with an entity or prop
![image](https://user-images.githubusercontent.com/34013112/208272064-56d58ae7-1d86-44ea-98ed-d6ada00e7fd2.png)

**Comment by Luiggi33** [comment]
I forgot to for hit world, but how to would you get into it anyway xd

**Comment by Luiggi33** [comment]
The question is, how should you be moved out, you can't no collide with the world... I would suggest that it will just respawn you

**Comment by MenschlichTv** [comment]
If we would want to make it clean and really usefull, you **could** search for the nearest empty position... but i think this would be too much work, I guess we can just ignore world collision then..
