### ISSUE TITLE
Job Spawn Ghosts not shown

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#18]
The Spawner tool makes no errors but I cant see any models, neither the ghost nor the "normal" one when you have the toolgun equipped

**Comment by Luiggi33** [comment]
![grafik](https://user-images.githubusercontent.com/41829216/208289437-4e525539-877a-4974-98b8-ac5d7452debf.png)
Still not replicable

**Comment by e8s1** [comment]
For me everything works fine
