### ISSUE TITLE
gware_utils_spawnnpc

### ISSUE THREAD

**Issue by StarLight-Oliver** [gmodWare/utils#22]
Distance check in the draw function, instead of DistToSQR. 

Color(0,0, 160) is constantly recreated in each frame even though it is static.

Minor, height gets shadowed "boxWidth" has been used so probably can go with fontHeight to avoid shadowing

**Comment by MenschlichTv** [comment]
> Minor, height gets shadowed "boxWidth" has been used so probably can go with fontHeight to avoid shadowing

What do you mean by that?

**Comment by Luiggi33** [comment]
~~I don't quite get the point with the boxWidth, the maxs and mins are related to the bounding box of the entity, and said size, not to the size of the text with a certain font.~~

**Comment by Luiggi33** [comment]
But I do understand that it uses the same variable, as my linter pointed out, I think I just understood that wrong. Correct me if I got something wrong
