### ISSUE TITLE
New Setting: Chat Bubbles

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#27]
Enable/Disable Chat bubbles when typing

**Comment by Luiggi33** [comment]
This is related to the darkrp chat indicator, right?

**Comment by Luiggi33** [comment]
To make this not hacky, DarkRP needs to be changed (https://github.com/FPtje/DarkRP/pull/3218)

**Comment by Luiggi33** [comment]
The pull request was accepted, I will add the option probably today

**Comment by Luiggi33** [comment]
The PR was accepted, will add the option soon

**Comment by Luiggi33** [comment]
The newest DarkRP version from GitHub is required for this one
