### ISSUE TITLE
Bug: g_VoicePanelList is nil sometimes on user join

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#37]
[gware] addons/gware/lua/gware-utils/settings/cl_settings.lua:14: attempt to index global 'g_VoicePanelList' (a nil value)
  1. fn - addons/gware/lua/gware-utils/settings/cl_settings.lua:14
   2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
    3. func - addons/gware/lua/gware-utils/networking/cl_net.lua:22
     4. unknown - lua/includes/extensions/net.lua:33

**Comment by Luiggi33** [comment]
As referenced in the commit, this should fix this bug. I did not have the chance to test it, so i cannot confirm

**Comment by Luiggi33** [comment]
It seems fixed, so I will close this
