### ISSUE TITLE
wont work with ULX right now

### ISSUE THREAD

**Issue by MenschlichTv** [gmodWare/utils#7]
We add the CAMI/SAM permissions when SAM has loaded, but if there is no sam installed, the CAMI permissions will never be added. This has to be fixed in a way that it works for both ULX and SAM

**Comment by Luiggi33** [comment]
Found the Issue, the permissions are added in a hook, that is only run if you have sam installed.
`hook.Add("SAM.LoadedConfig", "gWare.Utils.SamModules.WaitForClient", function()`

**Comment by Luiggi33** [comment]
Should be fixed with #8

**Comment by MenschlichTv** [comment]
fixed by luggi
